<template>
  <codeBox title="固定侧边栏 " description="当内容较长时，使用固定侧边栏可以提供更好的体验。" :code="fixedSideLayoutCode">
    <div class="fixedSideLayout">
      <iframe src="https://antdv.com/iframe/layout/#fixed-sider" height="360" width="100%" frameborder="0"></iframe>
      <!-- <ik-layout id="components-layout-demo-fixed-sider">
        <ik-layout-sider :style="{ overflow: 'auto', height: '100vh', position: 'fixed', left: 0 }">
          <div class="logo"></div>
          <ik-menu theme="dark" mode="inline" :defaultSelectedKeys="['4']">
            <ik-menu-item key="1">
              <ik-icon type="user" />
              <span class="nav-text">nav 1</span>
            </ik-menu-item>
            <ik-menu-item key="2">
              <ik-icon type="video-camera" />
              <span class="nav-text">nav 2</span>
            </ik-menu-item>
            <ik-menu-item key="3">
              <ik-icon type="upload" />
              <span class="nav-text">nav 3</span>
            </ik-menu-item>
            <ik-menu-item key="4">
              <ik-icon type="bar-chart" />
              <span class="nav-text">nav 4</span>
            </ik-menu-item>
            <ik-menu-item key="5">
              <ik-icon type="cloud-o" />
              <span class="nav-text">nav 5</span>
            </ik-menu-item>
            <ik-menu-item key="6">
              <ik-icon type="appstore-o" />
              <span class="nav-text">nav 6</span>
            </ik-menu-item>
            <ik-menu-item key="7">
              <ik-icon type="team" />
              <span class="nav-text">nav 7</span>
            </ik-menu-item>
            <ik-menu-item key="8">
              <ik-icon type="shop" />
              <span class="nav-text">nav 8</span>
            </ik-menu-item>
          </ik-menu>
        </ik-layout-sider>
        <ik-layout :style="{ marginLeft: '200px' }">
          <ik-layout-header :style="{ background: '#fff', padding: 0 }" />
          <ik-layout-content :style="{ margin: '24px 16px 0', overflow: 'initial' }">
            <div :style="{ padding: '24px', background: '#fff', textAlign: 'center' }">
              ...
              <br />Really
              <br />...
              <br />...
              <br />...
              <br />long
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />...
              <br />content
            </div>
          </ik-layout-content>
          <ik-layout-footer :style="{ textAlign: 'center' }">Design</ik-layout-footer>
        </ik-layout>
      </ik-layout> -->
    </div>
  </codeBox>
</template>

<script>
import { fixedSideLayoutCode } from './../codeExample'
export default {
  data () {
    return {
      fixedSideLayoutCode
    }
  }
}
</script>

<style lang="scss">
.fixedSideLayout {
  // height: 360px;
  // overflow: hidden;
  #components-layout-demo-fixed-sider {
    height: 360px;
    overflow: auto;
    .ant-layout-sider.ant-layout-sider-dark {
      position: relative !important;
      height: 360px !important;
      overflow: auto;
    }
    .logo {
      height: 32px;
      background: rgba(255, 255, 255, 0.2);
      margin: 16px;
    }
    .ant-layout {
      margin-left: 0 !important;
    }
  }
}
</style>
